name: CI

on:
  pull_request:
  push:

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_KEY: ${{ secrets.GPG_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - name: Check source code formatting
      shell: bash
      run: sbt +scalafmtCheck +test:scalafmtCheck scalafmtSbtCheck
    - name: Build and Test
      shell: bash
      run: sbt +test
    - name: Publish
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      shell: bash
      run: |
        echo $GPG_KEY | base64 -d | gpg --import
        sbt +publish sonatypeBundleReleaseIfNotSnapshot
